### ISSUE TITLE
ITRANS alternatives doesn't work

### ISSUE THREAD

**Issue by grosmar** [indic-transliteration/sanscript.js#50]
When I use `aa` instead of `A` or any other double characters it got transliterated wrongly, also to IAST and devanagari.

Even lot of tests are broken because of this issue.

It would be also great if it would be possible to enforce aa instead of `A` (same with ii, uu) when transliterating TO ITRANS. Is it possible somehow?

**Comment by bwasty** [comment]
The configuration for these characters can be found here: https://github.com/indic-transliteration/common_maps/blob/master/roman/itrans.toml#L3-L7

I'd prefer the lowercase versions as well. You could either change that file, or create a new variant, maybe calling it `itrans_lower` or something like that.

**Comment by vvasuki** [comment]
> Even lot of tests are broken because of this issue.
> 

https://github.com/indic-transliteration/sanscript.js/actions indicates that the tests succeed. Can you write down a function call which will let us confirm if the bug exists?


> It would be also great if it would be possible to enforce aa instead of `A` (same with ii, uu) when transliterating TO ITRANS. Is it possible somehow?
> ...
> create a new variant, maybe calling it itrans_lower or something like that. 
> The configuration for these characters can be found here: https://github.com/indic-transliteration/common_maps/blob/master/roman/itrans.toml#L3-L7
> 

Yes - the above is an acceptable option. Make sure to fix the alternates lower in the file as well.

**Comment by grosmar** [comment]
> > Even lot of tests are broken because of this issue.
> 
> https://github.com/indic-transliteration/sanscript.js/actions indicates that the tests succeed. Can you write down a function call which will let us confirm if the bug exists?

For me the test/index.html shows the following: 108 assertions of 243 passed, 135 failed.

But I just modified this test to compare iast result instead of devanagari to prove it:
```
QUnit.test("Alternates", function () {
    const f = function (itrans1, itrans2, description) {
        const iast1 = Sanscript.t(itrans1, "itrans", "iast");
        const iast2 = Sanscript.t(itrans2, "itrans", "iast");
        QUnit.assert.equal(iast2, iast1, description);
    };

    f("A I U RRi RRI LLi LLI", "aa ii uu R^i R^I L^i L^I", "vowels");
    f("kA kI kU kRRi kRRI kLLi kLLI", "kaa kii kuu kR^i kR^I kL^i kL^I",
        "vowels (marks)");
    f("I U", "ee oo", "long I and U");
    f("kI kU", "kee koo", "long I and U (marks)");
    f("aM aM", "a.m a.n", "anusvara");
    f("~Na", "N^a", "na (kavarga)");
    f("ca", "cha", "ca");
    f("Cha Cha", "Ca chha", "cha");
    f("va", "wa", "va/wa");
    f("Sha Sha", "Sa shha", "sha (retroflex)");
    f("kSha kSha kSha", "kSa kshha xa", "ksha");
    f("j~na j~na", "GYa dnya", "jna");
    f("OM", "AUM", "om");
    f(".a | ||", "~ . ..", "punctuation");
    f("za", "Ja", "Devanagari za");
    f("a{\\m+}", "a.h.N", "{\\m+}");
});
```

And the result was:
```
vowels@ 0 ms
Expected: 	
"ā ī ū ṟṟi ṟṟī l̤l̤i l̤l̤ī"
Result: 	
"aa ii uu ṟ^i ṟ^ī l̤^i l̤^ī"
Diff: 	
"ā ī ū ṟṟi ṟṟaa ii uu ṟ^i ṟ^ī l̤l̤^i l̤l̤^ī"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:552:5)
vowels (marks)@ 1 ms
Expected: 	
"kā kī kū kṟṟi kṟṟī kl̤l̤i kl̤l̤ī"
Result: 	
"kaa kii kuu kṟ^i kṟ^ī kl̤^i kl̤^ī"
Diff: 	
"kā kī kū kṟṟaa kii kuu kṟ^i kṟṟ^ī kl̤l̤^i kl̤l̤^ī"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:553:5)
long I and U@ 1 ms
Expected: 	
"ī ū"
Result: 	
"ee oo"
Diff: 	
"ī ūee oo"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:555:5)
long I and U (marks)@ 2 ms
Expected: 	
"kī kū"
Result: 	
"kee koo"
Diff: 	
"kī kūee koo"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:556:5)
anusvara@ 2 ms
Expected: 	
"aṃ aṃ"
Result: 	
"a|m a|n"
Diff: 	
"aṃ aṃ|m a|n"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:557:5)
na (kavarga)@ 2 ms
Expected: 	
"'ṇa"
Result: 	
"ṇ^a"
Diff: 	
"'ṇ^a"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:558:5)
ca@ 3 ms
Expected: 	
"ca"
Result: 	
"cha"
Diff: 	
"cha"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:559:5)
cha@ 3 ms
Expected: 	
"chha chha"
Result: 	
"cha chha"
Diff: 	
"chha chha"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:560:5)
va/wa@ 3 ms
sha (retroflex)@ 3 ms
Expected: 	
"ṣha ṣha"
Result: 	
"ṣa shha"
Diff: 	
"ṣha ṣshha"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:562:5)
ksha@ 4 ms
Expected: 	
"kṣha kṣha kṣha"
Result: 	
"kṣa kshha kṣa"
Diff: 	
"kṣha kṣshha kṣha"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:563:5)
jna@ 4 ms
Expected: 	
"j'na j'na"
Result: 	
"ġẏa dnya"
Diff: 	
"j'na j'nġẏa dnya"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:564:5)
om@ 4 ms
Expected: 	
"Oṃ"
Result: 	
"āūṃ"
Diff: 	
"Oāūṃ"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:565:5)
punctuation@ 5 ms
Expected: 	
"|a | ||"
Result: 	
"' | ||"
Diff: 	
"|a' | ||"
Source: 	
    at f (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:549:22)
    at Object.<anonymous> (file:///D:/GIT-REPOS/sc/sanscript.js/test/tests.js:566:5)
Devanagari za@ 5 ms
{\m+}
```

> 
> > It would be also great if it would be possible to enforce aa instead of `A` (same with ii, uu) when transliterating TO ITRANS. Is it possible somehow?
> > ...
> > create a new variant, maybe calling it itrans_lower or something like that.
> > The configuration for these characters can be found here: https://github.com/indic-transliteration/common_maps/blob/master/roman/itrans.toml#L3-L7
> 
> Yes - the above is an acceptable option. Make sure to fix the alternates lower in the file as well.

Okay, going to create a new itrans_lowercase and send PR.

**Comment by grosmar** [comment]
Yes, but I build on windows, so I needed to modify the build to:
so i run:
1. git checkout
2. `npm install`
3. `npm run build && npx babel.cmd sanscript.es6.js --out-file sanscript.js`
4. `npm run test`

maybe windows build or babel breaks somehow?

**Comment by vvasuki** [comment]
> Yes, but I build on windows, so I needed to modify the build to: so i run:
> 
>     1. git checkout
> 
>     2. `npm install`
> 
>     3. `npm run build && npx babel.cmd sanscript.es6.js --out-file sanscript.js`

Why not `npm run dist` instead of the above?

**Comment by grosmar** [comment]
As `transpile` script breaks with some error:
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at Object.compileFunction (node:vm:352:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1033:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1069:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m
```

And back in the time if I remember will I ended up figuring out it's because of the babel script.
But as you can see the rest is the same.

**Comment by vvasuki** [comment]
I see - can you contribute your babel.cmd and update the README with instructions for Windows users (with a note that tests fail on Windows only and a link to this thread) then?

**Comment by grosmar** [comment]
Fixed windows build, and added tests for ITRANS lowercase schema:
https://github.com/indic-transliteration/sanscript.js/pull/51

**Comment by grosmar** [comment]
However thinking about an alternative solution:
what if Sanscript would have a new config, where the user could set the preferred alternate, and this way we would avoid duplicated schema definitions.

Something like this:
```js
const conf  = {
  preferredAlternates: {"A": "aa", "I":"ii", "U": "uu", "j~n": "GY" }
};
Sanscript.t("śivāya", "iast", "itrans", conf);
```

So anywould could pick his/her preferred style of itrans, and we could avoid tons of duplications.

**Comment by vvasuki** [comment]
> However thinking about an alternative solution: what if Sanscript would have a new config, where the user could set the preferred alternate, and this way we would avoid duplicated schema definitions.

Given the low downside, we can keep the new schema definition.

> 
> Something like this:
> 
> ```js
> const conf  = {
>   preferredAlternates: {"A": "aa", "I":"ii", "U": "uu", "j~n": "GY" }
> };
> Sanscript.t("śivāya", "iast", "itrans", conf);
> ```
> 

Some config handling is welcome (analogous to what we have in the [py version](https://github.com/indic-transliteration/indic_transliteration_py/blob/de1cf2e6d4567d3f5a72ecbfa11f58812ba1f5f7/indic_transliteration/sanscript/__init__.py#L185) )
This particular alternates could be simply implemented as a sequence of replacements before returning, for now.

**Comment by grosmar** [comment]
Okay, will create something, and will show it to you soon.
I would also add support in the `Sanscript.default`:
```
Sanscript.defaults = {
        "skip_sgml" : false,
        "syncope"   : false,
        "preferred_alternates": 
          {"itrans": { "A": "aa", "I": "ii", "U": "uu", "j~n": "GY"}
    };
```

So would not need to set it all the times...

**Comment by vvasuki** [comment]
I don't share your preference for the lower case stuff (and so might others) - so let's not make it default.

**Comment by grosmar** [comment]
Sorry, I was not clear enough. I just said there could be default setting option, which by default would be empty, but anyone could overwrite it at the beginning of his/her project, so no need to set it up all the time.

**Comment by grosmar** [comment]
Have a look at this PR, for a proposed solution: https://github.com/indic-transliteration/sanscript.js/pull/52

Created a test case showing it's usage: https://github.com/indic-transliteration/sanscript.js/pull/52/commits/bf5beebbd25ae42170b9146e03731e8d3073029a#diff-6db27cd01f7a95b7fbc2d76b396eaec1957abbe8ec3198385c95e38e0a4909ddR527

**Comment by grosmar** [comment]
Still, if you like it I would get rid of this itrans_lowercase. Will be much harder to maintain later two itrans solutions, I found already some hardcoded itrans refernces in the source. Especially as this is only one combination of the many preferred alternates

**Comment by vvasuki** [comment]
Thanks (Changes should be published to npm now.)! We'll keep itrans_lowercase because:

- preferred_alternates can mess up escaped/ untransliterated texts - so, caller might not be able to use them in some cases.
- Useful for python etc.. libraries, where preferred alternates is not implemented.
