### ISSUE TITLE
Wylie transliteration

### ISSUE THREAD

**Issue by ayya-vimala** [indic-transliteration/sanscript.js#56]
Thank you for a great library. Would it be possible to add Wylie to it? I think it should not be so hard to add.

**Comment by vvasuki** [comment]
https://en.wikipedia.org/wiki/Wylie_transliteration doesn't cover many sanskrit sounds, and other Indic scripts don't cover many Tibetan sounds. So, it isn't clear what "adding" would mean.

**Comment by ayya-vimala** [comment]
extended Wylie should be able to convert without loss since sanskrit transliterations occur in Tibetan (especially in names of people, texts, places etc.). Extended Wylie (EWTS) is today's de-facto standard for computer software working with Wylie. https://www.thlib.org/reference/transliteration/teachingewts.pdf

**Comment by vvasuki** [comment]
[wylie.txt](https://github.com/indic-transliteration/sanscript.js/files/9349827/wylie.txt)

I'm still unclear about the encoding of some sanskrit sounds - please edit the attached file and revert.

**Comment by ayya-vimala** [comment]
Thanks so much! I just want to double check with somebody at the university when he is back from holiday next week. I will get back to you on this.

**Comment by ayya-vimala** [comment]
I checked back with the person at the university and he checked your codebase as well. He said:

> tibetan script is not just a 1:1 mapping, but the individual position of the characters is very improtant as well since there are many stacked letters, prescripts, postscripts, subscript, superscript

He checked out your code but felt that it is lacking the correct handling for the stacked letters to be able to add Wylie in this way with a 1-1 script.

So unfortunately I think we might have to abandon this route and I offer my sincere apologies that I was unaware of the extra difficulties Tibetan<->Wylie poses as opposed to other Asian scripts. It seemed a lot easier to me than it actually was.
