### ISSUE TITLE
Can the preinstall script be removed ?

### ISSUE THREAD

**Issue by lorefnon** [indic-transliteration/sanscript.js#64]
Hello, thanks for creating this repo. 

Curious if this [preinstall script](https://github.com/indic-transliteration/sanscript.js/blob/master/package.json#L14) is still needed ? From the discussion [here](https://github.com/indic-transliteration/sanscript.js/issues/54) it seems that you were using submodules before but migrated away from that. The current [list of submodules](https://github.com/indic-transliteration/sanscript.js/blob/master/.gitmodules) is just empty.

Unless you plan on adding any more submodules in near future, it would be good to remove this because this causes npm install or npm ci to fail in scenarios where the consumer project is not a git repo. We encountered this when running npm ci inside a docker container - we don't clone the whole of our repo into the image.

**Comment by vvasuki** [comment]
Please remove, test and send pull request.
